### ISSUE TITLE
what is the library version  compile 'com.github.avito-tech:krop:VERSION'

### ISSUE THREAD

**Issue by imvikasrai** [avito-tech/krop#18]
what is the library version  compile 'com.github.avito-tech:krop:VERSION'..what is VERSION stands for ?

**Comment by solkin** [comment]
Latest version for now is 0.44 as it shown in the JitPack badge [![JitPack](https://jitpack.io/v/avito-tech/krop.svg)](https://jitpack.io/#avito-tech/krop)

**Comment by imvikasrai** [comment]
ok thanks
