### ISSUE TITLE
getCropRect is private :(

### ISSUE THREAD

**Issue by JWvanV** [avito-tech/krop#8]
I'd love to use this rectangle, but that doesn't work if the method is private ;)

**Comment by solkin** [comment]
Sorry for this inconvenience.
For now, you can use method `getTransformation()`, that returns `Transformation` object.

**Comment by JWvanV** [comment]
I did find that method, no worries :)
I was also wondering if it would be possible to apply an initial cropping (instead of the default center crop) when setting the image uri.

The use case would be that a user crops an image in an activity, saves this and closes the activity, but would be able to adjust the cropping again, by re-opening the activity, where the stored cropping would be applied initially on the whole image.

**Comment by solkin** [comment]
For now, `KropView` can save state and restore. But, of course, it will be helpful to manually restore state.

**Comment by Kutashov** [comment]
@Spoetnic Hi, there!
It is better late, than never: we have the `getTransformation()` and `setTransformation()` methods for restoring images' state.
You don't need to use `getCropRect()` anymore.

**Comment by Kutashov** [comment]
I suppose we've done here, I close this issue.
